### ISSUE TITLE
requests.exceptions.MissingSchema: Invalid URL u'/sub/2015/06/14354008921381.rar': No schema supplied. Perhaps you meant http:///sub/2015/06/14354008921381.rar?

### ISSUE THREAD

**Issue by ruradium** [pa4373/subhd.py#1]
Looks like in subhd_py/core.py
https://github.com/pa4373/subhd.py/blob/master/subhd_py/core.py#L79

the real_addr dose not contain the domain name.
change to real_addr = 0'http://subhd.com/{0}'.format(res_with_real_addr.get('url')) will fix this issue

**Comment by pa4373** [comment]
Ohh, it looks wired, I would dig into that later, thanks.

In the meanwhile, could you tell me what you do so I can reproduce the bug? thanks.

**Comment by ruradium** [comment]
Wired, I cannot reproduce this bug today.

**Comment by pa4373** [comment]
Yeah, I found that you searched with 'while we were young' and tried to download every subtitle one by one and it succeed without any problem.

**Comment by pa4373** [comment]
(Cannot reproduce the bug.)
